version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(name)s][%(levelname)s] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO

root:
  level: WARNING
  handlers: [console]

loggers:
  SMARTS:
    level: WARNING
  SensorManager:
    level: WARNING
  your_code_module:
    level: INFO
