from smarts.core.plan import NavigationMission, Start, PositionalGoal
from typing import Any, Dict
from smarts.core.coordinates import Point, Heading
import numpy as np

def get_scenario_missions(scenario_id: int) -> Any:
    """
    Returns the scenario based on the scenario_id.
    """
    if scenario_id < 0 or scenario_id >= len(all_scenarios):
        raise ValueError(f"Invalid scenario_id: {scenario_id}. Must be between 0 and {len(all_scenarios) - 1}.")
    
    scenario = all_scenarios[scenario_id]
    
    missions = [
        NavigationMission(
            start=starting_points[trip[0]],
            goal=goal_points[trip[1]],
        ) for trip in scenario
    ]
    
    return missions


starting_points: Dict[str, Start] = {
    "east": Start(
        position=np.array([66.76, 40.62, 0.0]),
        heading=Heading(1.5707963267948966),  # Facing north
        from_front_bumper=True,
    ),
    "west": Start(
        position=np.array([10.0, 37.42, 0.0]),
        heading=Heading(-1.5707963267948966),  # Facing south
        from_front_bumper=True,
    ),
    "north": Start(
        position=np.array([36.82341976, 66.17009426, 0.0]),
        heading=Heading(3.141592653589793),  # Facing west
        from_front_bumper=True,
    ),
    "south": Start(
        position=np.array([40.14, 10.0, 0.0]),
        heading=Heading(0.0),  # Facing east
        from_front_bumper=True,
    ),
}

goal_points: Dict[str, PositionalGoal] = {
    "west": PositionalGoal(position=Point(10.0, 40.62, 0.0), radius=1.0),
    "east": PositionalGoal(position=Point(66.76, 37.42, 0.0), radius=1.0),
    "north": PositionalGoal(position=Point(39.98, 66.19, 0.0), radius=1.0),
    "south": PositionalGoal(position=Point(36.94, 10.0, 0.0), radius=1.0),
}


all_scenarios = [
    [('east', 'west')],
    [('east', 'north')],
    [('east', 'south')],
    [('west', 'east')],
    [('west', 'north')],
    [('west', 'south')],
    [('north', 'east')],
    [('north', 'west')],
    [('north', 'south')],
    [('south', 'east')],
    [('south', 'west')],
    [('south', 'north')],
    [('east', 'west'), ('west', 'east')],
    [('east', 'west'), ('west', 'north')],
    [('east', 'west'), ('west', 'south')],
    [('east', 'north'), ('west', 'east')],
    [('east', 'north'), ('west', 'north')],
    [('east', 'north'), ('west', 'south')],
    [('east', 'south'), ('west', 'east')],
    [('east', 'south'), ('west', 'north')],
    [('east', 'south'), ('west', 'south')],
    [('east', 'west'), ('north', 'east')],
    [('east', 'west'), ('north', 'west')],
    [('east', 'west'), ('north', 'south')],
    [('east', 'north'), ('north', 'east')],
    [('east', 'north'), ('north', 'west')],
    [('east', 'north'), ('north', 'south')],
    [('east', 'south'), ('north', 'east')],
    [('east', 'south'), ('north', 'west')],
    [('east', 'south'), ('north', 'south')],
    [('east', 'west'), ('south', 'east')],
    [('east', 'west'), ('south', 'west')],
    [('east', 'west'), ('south', 'north')],
    [('east', 'north'), ('south', 'east')],
    [('east', 'north'), ('south', 'west')],
    [('east', 'north'), ('south', 'north')],
    [('east', 'south'), ('south', 'east')],
    [('east', 'south'), ('south', 'west')],
    [('east', 'south'), ('south', 'north')],
    [('west', 'east'), ('north', 'east')],
    [('west', 'east'), ('north', 'west')],
    [('west', 'east'), ('north', 'south')],
    [('west', 'north'), ('north', 'east')],
    [('west', 'north'), ('north', 'west')],
    [('west', 'north'), ('north', 'south')],
    [('west', 'south'), ('north', 'east')],
    [('west', 'south'), ('north', 'west')],
    [('west', 'south'), ('north', 'south')],
    [('west', 'east'), ('south', 'east')],
    [('west', 'east'), ('south', 'west')],
    [('west', 'east'), ('south', 'north')],
    [('west', 'north'), ('south', 'east')],
    [('west', 'north'), ('south', 'west')],
    [('west', 'north'), ('south', 'north')],
    [('west', 'south'), ('south', 'east')],
    [('west', 'south'), ('south', 'west')],
    [('west', 'south'), ('south', 'north')],
    [('north', 'east'), ('south', 'east')],
    [('north', 'east'), ('south', 'west')],
    [('north', 'east'), ('south', 'north')],
    [('north', 'west'), ('south', 'east')],
    [('north', 'west'), ('south', 'west')],
    [('north', 'west'), ('south', 'north')],
    [('north', 'south'), ('south', 'east')],
    [('north', 'south'), ('south', 'west')],
    [('north', 'south'), ('south', 'north')],
    [('east', 'west'), ('west', 'east'), ('north', 'east')],
    [('east', 'west'), ('west', 'east'), ('north', 'west')],
    [('east', 'west'), ('west', 'east'), ('north', 'south')],
    [('east', 'west'), ('west', 'north'), ('north', 'east')],
    [('east', 'west'), ('west', 'north'), ('north', 'west')],
    [('east', 'west'), ('west', 'north'), ('north', 'south')],
    [('east', 'west'), ('west', 'south'), ('north', 'east')],
    [('east', 'west'), ('west', 'south'), ('north', 'west')],
    [('east', 'west'), ('west', 'south'), ('north', 'south')],
    [('east', 'north'), ('west', 'east'), ('north', 'east')],
    [('east', 'north'), ('west', 'east'), ('north', 'west')],
    [('east', 'north'), ('west', 'east'), ('north', 'south')],
    [('east', 'north'), ('west', 'north'), ('north', 'east')],
    [('east', 'north'), ('west', 'north'), ('north', 'west')],
    [('east', 'north'), ('west', 'north'), ('north', 'south')],
    [('east', 'north'), ('west', 'south'), ('north', 'east')],
    [('east', 'north'), ('west', 'south'), ('north', 'west')],
    [('east', 'north'), ('west', 'south'), ('north', 'south')],
    [('east', 'south'), ('west', 'east'), ('north', 'east')],
    [('east', 'south'), ('west', 'east'), ('north', 'west')],
    [('east', 'south'), ('west', 'east'), ('north', 'south')],
    [('east', 'south'), ('west', 'north'), ('north', 'east')],
    [('east', 'south'), ('west', 'north'), ('north', 'west')],
    [('east', 'south'), ('west', 'north'), ('north', 'south')],
    [('east', 'south'), ('west', 'south'), ('north', 'east')],
    [('east', 'south'), ('west', 'south'), ('north', 'west')],
    [('east', 'south'), ('west', 'south'), ('north', 'south')],
    [('east', 'west'), ('west', 'east'), ('south', 'east')],
    [('east', 'west'), ('west', 'east'), ('south', 'west')],
    [('east', 'west'), ('west', 'east'), ('south', 'north')],
    [('east', 'west'), ('west', 'north'), ('south', 'east')],
    [('east', 'west'), ('west', 'north'), ('south', 'west')],
    [('east', 'west'), ('west', 'north'), ('south', 'north')],
    [('east', 'west'), ('west', 'south'), ('south', 'east')],
    [('east', 'west'), ('west', 'south'), ('south', 'west')],
    [('east', 'west'), ('west', 'south'), ('south', 'north')],
    [('east', 'north'), ('west', 'east'), ('south', 'east')],
    [('east', 'north'), ('west', 'east'), ('south', 'west')],
    [('east', 'north'), ('west', 'east'), ('south', 'north')],
    [('east', 'north'), ('west', 'north'), ('south', 'east')],
    [('east', 'north'), ('west', 'north'), ('south', 'west')],
    [('east', 'north'), ('west', 'north'), ('south', 'north')],
    [('east', 'north'), ('west', 'south'), ('south', 'east')],
    [('east', 'north'), ('west', 'south'), ('south', 'west')],
    [('east', 'north'), ('west', 'south'), ('south', 'north')],
    [('east', 'south'), ('west', 'east'), ('south', 'east')],
    [('east', 'south'), ('west', 'east'), ('south', 'west')],
    [('east', 'south'), ('west', 'east'), ('south', 'north')],
    [('east', 'south'), ('west', 'north'), ('south', 'east')],
    [('east', 'south'), ('west', 'north'), ('south', 'west')],
    [('east', 'south'), ('west', 'north'), ('south', 'north')],
    [('east', 'south'), ('west', 'south'), ('south', 'east')],
    [('east', 'south'), ('west', 'south'), ('south', 'west')],
    [('east', 'south'), ('west', 'south'), ('south', 'north')],
    [('east', 'west'), ('north', 'east'), ('south', 'east')],
    [('east', 'west'), ('north', 'east'), ('south', 'west')],
    [('east', 'west'), ('north', 'east'), ('south', 'north')],
    [('east', 'west'), ('north', 'west'), ('south', 'east')],
    [('east', 'west'), ('north', 'west'), ('south', 'west')],
    [('east', 'west'), ('north', 'west'), ('south', 'north')],
    [('east', 'west'), ('north', 'south'), ('south', 'east')],
    [('east', 'west'), ('north', 'south'), ('south', 'west')],
    [('east', 'west'), ('north', 'south'), ('south', 'north')],
    [('east', 'north'), ('north', 'east'), ('south', 'east')],
    [('east', 'north'), ('north', 'east'), ('south', 'west')],
    [('east', 'north'), ('north', 'east'), ('south', 'north')],
    [('east', 'north'), ('north', 'west'), ('south', 'east')],
    [('east', 'north'), ('north', 'west'), ('south', 'west')],
    [('east', 'north'), ('north', 'west'), ('south', 'north')],
    [('east', 'north'), ('north', 'south'), ('south', 'east')],
    [('east', 'north'), ('north', 'south'), ('south', 'west')],
    [('east', 'north'), ('north', 'south'), ('south', 'north')],
    [('east', 'south'), ('north', 'east'), ('south', 'east')],
    [('east', 'south'), ('north', 'east'), ('south', 'west')],
    [('east', 'south'), ('north', 'east'), ('south', 'north')],
    [('east', 'south'), ('north', 'west'), ('south', 'east')],
    [('east', 'south'), ('north', 'west'), ('south', 'west')],
    [('east', 'south'), ('north', 'west'), ('south', 'north')],
    [('east', 'south'), ('north', 'south'), ('south', 'east')],
    [('east', 'south'), ('north', 'south'), ('south', 'west')],
    [('east', 'south'), ('north', 'south'), ('south', 'north')],
    [('west', 'east'), ('north', 'east'), ('south', 'east')],
    [('west', 'east'), ('north', 'east'), ('south', 'west')],
    [('west', 'east'), ('north', 'east'), ('south', 'north')],
    [('west', 'east'), ('north', 'west'), ('south', 'east')],
    [('west', 'east'), ('north', 'west'), ('south', 'west')],
    [('west', 'east'), ('north', 'west'), ('south', 'north')],
    [('west', 'east'), ('north', 'south'), ('south', 'east')],
    [('west', 'east'), ('north', 'south'), ('south', 'west')],
    [('west', 'east'), ('north', 'south'), ('south', 'north')],
    [('west', 'north'), ('north', 'east'), ('south', 'east')],
    [('west', 'north'), ('north', 'east'), ('south', 'west')],
    [('west', 'north'), ('north', 'east'), ('south', 'north')],
    [('west', 'north'), ('north', 'west'), ('south', 'east')],
    [('west', 'north'), ('north', 'west'), ('south', 'west')],
    [('west', 'north'), ('north', 'west'), ('south', 'north')],
    [('west', 'north'), ('north', 'south'), ('south', 'east')],
    [('west', 'north'), ('north', 'south'), ('south', 'west')],
    [('west', 'north'), ('north', 'south'), ('south', 'north')],
    [('west', 'south'), ('north', 'east'), ('south', 'east')],
    [('west', 'south'), ('north', 'east'), ('south', 'west')],
    [('west', 'south'), ('north', 'east'), ('south', 'north')],
    [('west', 'south'), ('north', 'west'), ('south', 'east')],
    [('west', 'south'), ('north', 'west'), ('south', 'west')],
    [('west', 'south'), ('north', 'west'), ('south', 'north')],
    [('west', 'south'), ('north', 'south'), ('south', 'east')],
    [('west', 'south'), ('north', 'south'), ('south', 'west')],
    [('west', 'south'), ('north', 'south'), ('south', 'north')],
    [('east', 'west'), ('west', 'east'), ('north', 'east'), ('south', 'east')],
    [('east', 'west'), ('west', 'east'), ('north', 'east'), ('south', 'west')],
    [('east', 'west'), ('west', 'east'), ('north', 'east'), ('south', 'north')],
    [('east', 'west'), ('west', 'east'), ('north', 'west'), ('south', 'east')],
    [('east', 'west'), ('west', 'east'), ('north', 'west'), ('south', 'west')],
    [('east', 'west'), ('west', 'east'), ('north', 'west'), ('south', 'north')],
    [('east', 'west'), ('west', 'east'), ('north', 'south'), ('south', 'east')],
    [('east', 'west'), ('west', 'east'), ('north', 'south'), ('south', 'west')],
    [('east', 'west'), ('west', 'east'), ('north', 'south'), ('south', 'north')],
    [('east', 'west'), ('west', 'north'), ('north', 'east'), ('south', 'east')],
    [('east', 'west'), ('west', 'north'), ('north', 'east'), ('south', 'west')],
    [('east', 'west'), ('west', 'north'), ('north', 'east'), ('south', 'north')],
    [('east', 'west'), ('west', 'north'), ('north', 'west'), ('south', 'east')],
    [('east', 'west'), ('west', 'north'), ('north', 'west'), ('south', 'west')],
    [('east', 'west'), ('west', 'north'), ('north', 'west'), ('south', 'north')],
    [('east', 'west'), ('west', 'north'), ('north', 'south'), ('south', 'east')],
    [('east', 'west'), ('west', 'north'), ('north', 'south'), ('south', 'west')],
    [('east', 'west'), ('west', 'north'), ('north', 'south'), ('south', 'north')],
    [('east', 'west'), ('west', 'south'), ('north', 'east'), ('south', 'east')],
    [('east', 'west'), ('west', 'south'), ('north', 'east'), ('south', 'west')],
    [('east', 'west'), ('west', 'south'), ('north', 'east'), ('south', 'north')],
    [('east', 'west'), ('west', 'south'), ('north', 'west'), ('south', 'east')],
    [('east', 'west'), ('west', 'south'), ('north', 'west'), ('south', 'west')],
    [('east', 'west'), ('west', 'south'), ('north', 'west'), ('south', 'north')],
    [('east', 'west'), ('west', 'south'), ('north', 'south'), ('south', 'east')],
    [('east', 'west'), ('west', 'south'), ('north', 'south'), ('south', 'west')],
    [('east', 'west'), ('west', 'south'), ('north', 'south'), ('south', 'north')],
    [('east', 'north'), ('west', 'east'), ('north', 'east'), ('south', 'east')],
    [('east', 'north'), ('west', 'east'), ('north', 'east'), ('south', 'west')],
    [('east', 'north'), ('west', 'east'), ('north', 'east'), ('south', 'north')],
    [('east', 'north'), ('west', 'east'), ('north', 'west'), ('south', 'east')],
    [('east', 'north'), ('west', 'east'), ('north', 'west'), ('south', 'west')],
    [('east', 'north'), ('west', 'east'), ('north', 'west'), ('south', 'north')],
    [('east', 'north'), ('west', 'east'), ('north', 'south'), ('south', 'east')],
    [('east', 'north'), ('west', 'east'), ('north', 'south'), ('south', 'west')],
    [('east', 'north'), ('west', 'east'), ('north', 'south'), ('south', 'north')],
    [('east', 'north'), ('west', 'north'), ('north', 'east'), ('south', 'east')],
    [('east', 'north'), ('west', 'north'), ('north', 'east'), ('south', 'west')],
    [('east', 'north'), ('west', 'north'), ('north', 'east'), ('south', 'north')],
    [('east', 'north'), ('west', 'north'), ('north', 'west'), ('south', 'east')],
    [('east', 'north'), ('west', 'north'), ('north', 'west'), ('south', 'west')],
    [('east', 'north'), ('west', 'north'), ('north', 'west'), ('south', 'north')],
    [('east', 'north'), ('west', 'north'), ('north', 'south'), ('south', 'east')],
    [('east', 'north'), ('west', 'north'), ('north', 'south'), ('south', 'west')],
    [('east', 'north'), ('west', 'north'), ('north', 'south'), ('south', 'north')],
    [('east', 'north'), ('west', 'south'), ('north', 'east'), ('south', 'east')],
    [('east', 'north'), ('west', 'south'), ('north', 'east'), ('south', 'west')],
    [('east', 'north'), ('west', 'south'), ('north', 'east'), ('south', 'north')],
    [('east', 'north'), ('west', 'south'), ('north', 'west'), ('south', 'east')],
    [('east', 'north'), ('west', 'south'), ('north', 'west'), ('south', 'west')],
    [('east', 'north'), ('west', 'south'), ('north', 'west'), ('south', 'north')],
    [('east', 'north'), ('west', 'south'), ('north', 'south'), ('south', 'east')],
    [('east', 'north'), ('west', 'south'), ('north', 'south'), ('south', 'west')],
    [('east', 'north'), ('west', 'south'), ('north', 'south'), ('south', 'north')],
    [('east', 'south'), ('west', 'east'), ('north', 'east'), ('south', 'east')],
    [('east', 'south'), ('west', 'east'), ('north', 'east'), ('south', 'west')],
    [('east', 'south'), ('west', 'east'), ('north', 'east'), ('south', 'north')],
    [('east', 'south'), ('west', 'east'), ('north', 'west'), ('south', 'east')],
    [('east', 'south'), ('west', 'east'), ('north', 'west'), ('south', 'west')],
    [('east', 'south'), ('west', 'east'), ('north', 'west'), ('south', 'north')],
    [('east', 'south'), ('west', 'east'), ('north', 'south'), ('south', 'east')],
    [('east', 'south'), ('west', 'east'), ('north', 'south'), ('south', 'west')],
    [('east', 'south'), ('west', 'east'), ('north', 'south'), ('south', 'north')],
    [('east', 'south'), ('west', 'north'), ('north', 'east'), ('south', 'east')],
    [('east', 'south'), ('west', 'north'), ('north', 'east'), ('south', 'west')],
    [('east', 'south'), ('west', 'north'), ('north', 'east'), ('south', 'north')],
    [('east', 'south'), ('west', 'north'), ('north', 'west'), ('south', 'east')],
    [('east', 'south'), ('west', 'north'), ('north', 'west'), ('south', 'west')],
    [('east', 'south'), ('west', 'north'), ('north', 'west'), ('south', 'north')],
    [('east', 'south'), ('west', 'north'), ('north', 'south'), ('south', 'east')],
    [('east', 'south'), ('west', 'north'), ('north', 'south'), ('south', 'west')],
    [('east', 'south'), ('west', 'north'), ('north', 'south'), ('south', 'north')],
    [('east', 'south'), ('west', 'south'), ('north', 'east'), ('south', 'east')],
    [('east', 'south'), ('west', 'south'), ('north', 'east'), ('south', 'west')],
    [('east', 'south'), ('west', 'south'), ('north', 'east'), ('south', 'north')],
    [('east', 'south'), ('west', 'south'), ('north', 'west'), ('south', 'east')],
    [('east', 'south'), ('west', 'south'), ('north', 'west'), ('south', 'west')],
    [('east', 'south'), ('west', 'south'), ('north', 'west'), ('south', 'north')],
    [('east', 'south'), ('west', 'south'), ('north', 'south'), ('south', 'east')],
    [('east', 'south'), ('west', 'south'), ('north', 'south'), ('south', 'west')],
    [('east', 'south'), ('west', 'south'), ('north', 'south'), ('south', 'north')],
]

all_scenarios_to_number_of_agents = [
    len(scenario) for scenario in all_scenarios
]

scenarios_per_number_of_agents = {
    i: [j for j, scenario in enumerate(all_scenarios) if len(scenario) == i]
    for i in range(1, 1+ max(all_scenarios_to_number_of_agents)) 
}