communication_hidden_dim: [32, 16]
critic_hidden_dim: [128, 128, 32]
actor_hidden_dim: [128, 128, 32]

input_dim: [12, 32, 32]
action_dim: 1
direction_dim: 4
feature_dim: 64
message_dim: 8
n_agents: 4

tau: 0.005
gamma: 0.99
lr: 0.0001
alpha: 0.4
memory_max_size: 100000
batch_size: 258

reconstruction_coef: 0.1
reg_coef: 0.1
target_update_interval: 2
actor_update_frequency: 1
automatic_entropy_tuning: true
entropy_decay_rate: 0.0001

chkpt_dir: "models/${algorithm_identifier}"

evaluate: ${shared.evaluate}
parallel: ${shared.parallel}