communication_hidden_dim: [32, 16]
critic_hidden_dim: [128, 128, 32]
actor_hidden_dim: [128, 128, 32]

input_dim: [12, 128, 128]
action_dim: 1
direction_dim: 4
feature_dim: 64
message_dim: 5
n_agents: 4

tau: 0.005
gamma: 0.99
lr: 0.0001
memory_max_size: 10000
batch_size: 256
reconstruction_coef: 0.1
reg_coef: 0.1
target_update_interval: 1
actor_update_frequency: 1
entropy_decay_rate: 0.0001

alpha: 0.4
target_entropy: -0.4
automatic_entropy_tuning: true

chkpt_dir: "models/${algorithm_identifier}"

evaluate: ${shared.evaluate}